<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventoryItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('inventory_items')->insert([
            [
                'name' => 'Beef',
                'category' => 'Proteins',
                'unit' => 'kg',
                'quantity' => 50,
                'reorder_level' => 10,
                'unit_price' => 12000,
                'supplier' => 'Uganda Meat Supplies',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rice',
                'category' => 'Staples',
                'unit' => 'kg',
                'quantity' => 100,
                'reorder_level' => 20,
                'unit_price' => 4500,
                'supplier' => 'Kampala Grains Ltd',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cooking Oil',
                'category' => 'Oils & Liquids',
                'unit' => 'litres',
                'quantity' => 30,
                'reorder_level' => 5,
                'unit_price' => 8000,
                'supplier' => 'Bidco Uganda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tomatoes',
                'category' => 'Vegetables',
                'unit' => 'kg',
                'quantity' => 40,
                'reorder_level' => 10,
                'unit_price' => 3000,
                'supplier' => 'Mbarara Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Salt',
                'category' => 'Spices & Seasoning',
                'unit' => 'kg',
                'quantity' => 25,
                'reorder_level' => 5,
                'unit_price' => 1500,
                'supplier' => 'UgaSalt Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Goat Meat',
                'category' => 'Proteins',
                'unit' => 'kg',
                'quantity' => 30,
                'reorder_level' => 8,
                'unit_price' => 16000,
                'supplier' => 'Uganda Meat Supplies',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chicken (whole)',
                'category' => 'Proteins',
                'unit' => 'pcs',
                'quantity' => 25,
                'reorder_level' => 5,
                'unit_price' => 35000,
                'supplier' => 'Kakoba Poultry Farm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chicken (fillet)',
                'category' => 'Proteins',
                'unit' => 'kg',
                'quantity' => 60,
                'reorder_level' => 15,
                'unit_price' => 7000,
                'supplier' => 'UgaSalt Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fish (Tilapia, Nile Perch)',
                'category' => 'Proteins',
                'unit' => 'kg',
                'quantity' => 45,
                'reorder_level' => 15,
                'unit_price' => 10000,
                'supplier' => 'Katunguru Fishermen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eggs',
                'category' => 'Proteins',
                'unit' => 'tray (30 pcs)',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 15000,
                'supplier' => 'Kakoba Poultry Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Biryani Rice',
                'category' => 'Spices & Grains',
                'unit' => 'kg',
                'quantity' => 80,
                'reorder_level' => 20,
                'unit_price' => 6500,
                'supplier' => 'Kampala Grains Ltd',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Matooke',
                'category' => 'Spices & Grains',
                'unit' => 'bunch',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 20000,
                'supplier' => 'Mbarara Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Irish Potatoes',
                'category' => 'Spices & Grains',
                'unit' => 'kg',
                'quantity' => 300,
                'reorder_level' => 50,
                'unit_price' => 600,
                'supplier' => 'Kigezi Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sweet Potatoes',
                'category' => 'Spices & Grains',
                'unit' => 'kg',
                'quantity' => 150,
                'reorder_level' => 35,
                'unit_price' => 1000,
                'supplier' => 'Kigezi Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cassava',
                'category' => 'Spices & Grains',
                'unit' => 'kg',
                'quantity' => 100,
                'reorder_level' => 25,
                'unit_price' => 800,
                'supplier' => 'Bushenyi Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chappati Flour (wheat)',
                'category' => 'Spices & Grains',
                'unit' => 'kg',
                'quantity' => 50,
                'reorder_level' => 10,
                'unit_price' => 4000,
                'supplier' => 'Mandela Millers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maize Flour (posho)',
                'category' => 'Spices & Grains',
                'unit' => 'kg',
                'quantity' => 100,
                'reorder_level' => 25,
                'unit_price' => 3000,
                'supplier' => 'Mandela Millers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Onions',
                'category' => 'Vegetables',
                'unit' => 'kg',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 1500,
                'supplier' => 'Rwahi Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Green Pepper',
                'category' => 'Vegetables',
                'unit' => 'kg',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 2000,
                'supplier' => 'Ntungamo Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carrots',
                'category' => 'Vegetables',
                'unit' => 'kg',
                'quantity' => 25,
                'reorder_level' => 5,
                'unit_price' => 3000,
                'supplier' => 'Ruhinda Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cabbage',
                'category' => 'Vegetables',
                'unit' => 'kg',
                'quantity' => 30,
                'reorder_level' => 10,
                'unit_price' => 2500,
                'supplier' => 'Kitagata Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sukuma Wiki (Kale)',
                'category' => 'Vegetables',
                'unit' => 'bunch',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 1500,
                'supplier' => 'Kigezi Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yellow',
                'category' => 'Vegetables',
                'unit' => 'bunch',
                'quantity' => 45,
                'reorder_level' => 15,
                'unit_price' => 4000,
                'supplier' => 'Mbarara Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ginger',
                'category' => 'Vegetables',
                'unit' => 'kg',
                'quantity' => 15,
                'reorder_level' => 5,
                'unit_price' => 2000,
                'supplier' => 'Rwampara Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Garlic',
                'category' => 'Vegetables',
                'unit' => 'kg',
                'quantity' => 15,
                'reorder_level' => 5,
                'unit_price' => 3500,
                'supplier' => 'Isingiro Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Egg Plant (Biringanya)',
                'category' => 'Vegetables',
                'unit' => 'kg',
                'quantity' => 25,
                'reorder_level' => 5,
                'unit_price' => 2500,
                'supplier' => 'Ibanda Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Royco',
                'category' => 'Spices and Seasoning',
                'unit' => 'grams',
                'quantity' => 850,
                'reorder_level' => 200,
                'unit_price' => 500,
                'supplier' => 'Mbarara Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Curry Powder',
                'category' => 'Spices & Seasoning',
                'unit' => 'grams',
                'quantity' => 700,
                'reorder_level' => 150,
                'unit_price' => 500,
                'supplier' => 'Mbarara Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Black Pepper',
                'category' => 'Spices & Seasoning',
                'unit' => 'grams',
                'quantity' => 1000,
                'reorder_level' => 2000,
                'unit_price' => 500,
                'supplier' => 'Mbarara Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Garam Masala',
                'category' => 'Spices & Seasoning',
                'unit' => 'grams',
                'quantity' => 1500,
                'reorder_level' => 350,
                'unit_price' => 500,
                'supplier' => 'UgaSalt Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pilau Masala',
                'category' => 'Spices & Seasoning',
                'unit' => 'grams',
                'quantity' => 3000,
                'reorder_level' => 500,
                'unit_price' => 500,
                'supplier' => 'Mbarara Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gumin (Jira)',
                'category' => 'Spices & Seasoning',
                'unit' => 'grams',
                'quantity' => 800,
                'reorder_level' => 150,
                'unit_price' => 500,
                'supplier' => 'Mbarara Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Coriander Powder',
                'category' => 'Spices & Seasoning',
                'unit' => 'grams',
                'quantity' => 900,
                'reorder_level' => 200,
                'unit_price' => 500,
                'supplier' => 'Mbarara Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paprika',
                'category' => 'Spices & Seasoning',
                'unit' => 'grams',
                'quantity' => 650,
                'reorder_level' => 100,
                'unit_price' => 500,
                'supplier' => 'Mbarara Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bay Leaves',
                'category' => 'Spices & Seasoning',
                'unit' => 'grams',
                'quantity' => 2500,
                'reorder_level' => 400,
                'unit_price' => 500,
                'supplier' => 'UgaSalt Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Groundnut Paste',
                'category' => 'Oils & Liquids',
                'unit' => 'kg',
                'quantity' => 25,
                'reorder_level' => 5,
                'unit_price' => 3500,
                'supplier' => 'Kamwenge Farmers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Milk',
                'category' => 'Oils & Liquids',
                'unit' => 'litres',
                'quantity' => 25,
                'reorder_level' => 5,
                'unit_price' => 1200,
                'supplier' => 'Nsanga Dairy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Water (Drinking)',
                'category' => 'Oils & Liquids',
                'unit' => 'boxes',
                'quantity' => 25,
                'reorder_level' => 5,
                'unit_price' => 20000,
                'supplier' => 'Rwenzori Water',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vinegar',
                'category' => 'Oils & Liquids',
                'unit' => 'litres',
                'quantity' => 25,
                'reorder_level' => 5,
                'unit_price' => 2500,
                'supplier' => 'Bidco Uganda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Soy Sauce',
                'category' => 'Oils & Liquids',
                'unit' => 'litres',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 3500,
                'supplier' => 'Bidco Uganda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cooking Cream',
                'category' => 'Oils & Liquids',
                'unit' => 'litres',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 4500,
                'supplier' => 'UgaSalt Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bread (Loaf)',
                'category' => 'Bakery/Breads',
                'unit' => 'pcs',
                'quantity' => 15,
                'reorder_level' => 5,
                'unit_price' => 5500,
                'supplier' => 'Ntake Bakery',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chappati (Ready - made)',
                'category' => 'Bakery/Breads',
                'unit' => 'pcs',
                'quantity' => 20,
                'reorder_level' => 15,
                'unit_price' => 8000,
                'supplier' => 'Ntake Bakery',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buns/Samosa',
                'category' => 'Bakery/Breads',
                'unit' => 'pcs',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 3000,
                'supplier' => 'Ntake Bakery',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Soda (various brands)',
                'category' => 'Drinks & Beverages',
                'unit' => 'crates',
                'quantity' => 10,
                'reorder_level' => 5,
                'unit_price' => 20000,
                'supplier' => 'Mbarara Depot',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Juice Concentrate',
                'category' => 'Drinks & Beverages',
                'unit' => 'litres',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 1500,
                'supplier' => 'Dinah Enterprises',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Coffee Powder',
                'category' => 'Drinks & Beverages',
                'unit' => 'grams',
                'quantity' => 5000,
                'reorder_level' => 500,
                'unit_price' => 500,
                'supplier' => 'Rubanga Coffee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tea Leaves',
                'category' => 'Drinks & Beverages',
                'unit' => 'grams',
                'quantity' => 5000,
                'reorder_level' => 500,
                'unit_price' => 500,
                'supplier' => 'Kigezi Highland Tea',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sugar',
                'category' => 'Drinks & Beverages',
                'unit' => 'kg',
                'quantity' => 25,
                'reorder_level' => 10,
                'unit_price' => 5000,
                'supplier' => 'Kakira',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wine',
                'category' => 'Drinkss & Beverages',
                'unit' => 'bottles',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 7500,
                'supplier' => 'Nzeyi Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beer',
                'category' => 'Drinks & Beverages',
                'unit' => 'crates',
                'quantity' => 15,
                'reorder_level' => 5,
                'unit_price' => 100000,
                'supplier' => 'Nzeyi Distributors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gas',
                'category' => 'Kitchen Supplies/Others',
                'unit' => 'kg',
                'quantity' => 25,
                'reorder_level' => 5,
                'unit_price' => 5000,
                'supplier' => 'Stabex Ltd',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Detergent',
                'category' => 'Kitchen Supplies/Others',
                'unit' => 'litres',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 1000,
                'supplier' => 'Emma Enterprises',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tissues/Serviettes',
                'category' => 'Kitchen Supplies/Others',
                'unit' => 'pcs',
                'quantity' => 30,
                'reorder_level' => 10,
                'unit_price' => 2500,
                'supplier' => 'Emma Enterprises',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Foil/Cling Film',
                'category' => 'Kitchen Supplies/Others',
                'unit' => 'rolls',
                'quantity' => 20,
                'reorder_level' => 5,
                'unit_price' => 5000,
                'supplier' => 'Emma Enterprises',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
